logging:
  level:
    org.springframework.security: trace

server:
  port: 9000

app:
  credentials:
    sam: "password"
    frodo: "password"
    merry: "password"
    pippin: "password"

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          default-client:
            token:
              access-token-time-to-live: 1h
            registration:
              client-id: "default-client-id"
              client-secret: "{noop}default-client-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:6274/oauth/callback" # mcp-inspector
                - "http://localhost:6274/oauth/callback/debug" # mcp-inspector
              scopes:
                - "openid"