logging:
  level:
#    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.mcp: TRACE

server:
  port: 8081

spring:
  application:
    name: aidemo

  threads:
    virtual:
      enabled: true

  shell:
    script:
      enabled: true
    interactive:
      enabled: true

  ai:
    chat:
      client:
        enabled: true

    ollama:
      base-url: http://localhost:11434
      chat:
        model: mistral-nemo:latest
        options:
          top-p: 0.9
          top-k: 40
          temperature: 0.7

    mcp:
      client:
        enabled: true
        name: middle-earth-mcp-client
        type: SYNC
        request-timeout: 360s
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            hobbit-mcp-server:
              url: http://localhost:8080
              endpoint: /mcp
        annotation-scanner:
          enabled: true
